# Generated by Django 6.0.5 on 2026-05-10 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('d', 'Despesa'), ('r', 'Receita')], default='d', max_length=1, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('dataoperacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Operação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='contabil.conta', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['-dataoperacao', '-criado_em'],
            },
        ),
    ]
